[package]
name = "aoc2022"
version = "0.1.0"
edition = "2021"
authors = ["David Lavoie-Boutin"]
description = "Advent of Code, 2022 edition"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
